name: Build MiguIA APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest # Usamos la versión más nueva y estable
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          # Aquí está el truco: le decimos que no intente cambiar el dueño de los archivos
          save_buildozer_config: false 
        env:
          # Forzamos al sistema a saber quién es el usuario
          USER: root
