name: Build MiguIA APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Herramientas de Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-dev \
          zip unzip autoconf libtool lld aidl libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
          libavformat-dev libavcodec-dev zlib1g-dev

      - name: Instalar Buildozer y Cython
        run: |
          pip install --upgrade pip
          pip install "Cython<3.0" buildozer requests

      - name: Cocinar APK (Buildozer)
        run: |
          yes | buildozer -v android debug
        env:
          USER: root

      - name: Subir APK (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: MiguIA-Package
          path: bin/*.apk
