name: Build MiguIA APK
on: [push, workflow_dispatch]

jobs:
  build:
    # Esta versión arranca al instante y es muy estable
    runs-on: ubuntu-22.04 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build APK with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          buildozer_version: master
          save_buildozer_config: false
        env:
          USER: root
          # Este comando es el "abrete sésamo" para evitar el error de Python
          PIP_BREAK_SYSTEM_PACKAGES: 1
